export const pack = {
    hello: {
      info_data: 'приветствие',
      ru: 'Привет',
      en: 'Hello',
      es: 'Hola',
      fr: 'Bonjour',
      pt: 'Oi',
      de: 'Hallo',
      zh: '你好',
      it: 'Salve',
      ja: 'こんにちは',
      ko: '안녕하세요',
      ar: 'مرحبا',
      hi: 'नमस्ते',
      he: 'שָׁלוֹם',
      tr: 'Merhaba',
      vi: 'Xin chào',
      nl: 'Hallo',
      pl: 'Cześć',
      id: 'Halo',
      sv: 'Hej',
      cs: 'Ahoj',
      uk: 'Привіт',
      hu: 'Szia',
      th: 'สวัสดี',
      el: 'Γεια',
      da: 'Hej',
      fi: 'Hei.',
      ro: 'Salut',
      sk: 'Ahoj',
      be: 'Прывітанне'
    }
  }
